spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # copy from nacos console
        namespace: 3f21b39c-8476-4520-ac89-3ea4c0e1f47b
  application:
    name: user-service-provider

server:
  port: 8700

logging:
  config: classpath:logback-springboot.xml

print-server-address:
  ignore-parent-context: true

info:
  tags:
    environment: test
  app: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"