spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # copy from nacos console
        namespace: 7c97fbd8-4c03-4ad0-91dd-badb10956ea6
  application:
    name: user-service-provider

server:
  port: 8700

logging:
  config: classpath:logback-springboot.xml

print-server-address:
  ignore-parent-context: true

info:
  tags:
    environment: test
  app: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"